# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 11:44
from __future__ import unicode_literals

import bizzfuzz_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(null=True)),
                ('number', models.IntegerField(default=bizzfuzz_app.models.user.random_number_generate)),
            ],
        ),
    ]
