# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizzfuzz_app', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=b'1970-01-01'),
        ),
    ]
